"""Acceptance tests for the baseline AgentPackage and its primitive tools."""

import importlib
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
import yaml

from agentgym.core.package import AgentPackage

ROOT = Path(__file__).parents[2]
PACKAGE_DIR = ROOT / "packages" / "baseline"


@pytest.fixture(scope="module")
def baseline_server() -> ModuleType:
    """Import the server without adding generated bytecode to the package tree."""

    previous = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        return importlib.import_module("packages.baseline.mcp.server")
    finally:
        sys.dont_write_bytecode = previous


def test_baseline_package_loads_and_matches_domain_capabilities() -> None:
    """The persisted manifest and both package loading entry points are valid."""

    package = AgentPackage.load(PACKAGE_DIR)
    from_directory = AgentPackage.from_directory(PACKAGE_DIR)
    domain = yaml.safe_load((ROOT / "domains" / "confluence" / "domain.yaml").read_text())

    assert package == from_directory
    assert package.id == "baseline"
    assert package.version == "0.1"
    assert package.generation == 0
    assert package.parent_id is None
    assert package.tools.declared_capabilities == domain["capabilities"]
    assert package.skills == []


async def test_baseline_server_registers_only_primitive_tools(
    baseline_server: ModuleType,
) -> None:
    """The FastMCP registry contains exactly the §56 primitive set."""

    tools = await baseline_server.mcp.list_tools()

    assert {tool.name for tool in tools} == {
        "search_pages",
        "get_page",
        "get_page_versions",
        "create_page",
        "update_page",
    }


async def test_update_page_passes_version_to_raw_request(
    baseline_server: ModuleType,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The optimistic-lock version becomes the raw API If-Version value."""

    captured: dict[str, Any] = {}

    async def fake_request(method: str, path: str, **kwargs: Any) -> dict[str, Any]:
        captured.update(method=method, path=path, **kwargs)
        return {"id": "page-1", "version": 8, "body": "updated"}

    monkeypatch.setattr(baseline_server, "_request", fake_request)

    result = await baseline_server.update_page("page-1", 7, body="updated")

    assert result["version"] == 8
    assert captured == {
        "method": "PUT",
        "path": "/api/pages/page-1",
        "payload": {"body": "updated"},
        "if_version": 7,
    }
